### PR TITLE
[WIP] fixes Gellert5225/StellarEngine#8

### PR DESCRIPTION
**Pull request by Pjsrcool**

### CODE REVIEW

**Comment by Pjsrcool** [comment]
fixes Gellert5225/StellarEngine#8

**Comment by Gellert5225** [comment]
I had no issue compiling `imgui_widget`, but there's a couple of things worth mentioning:

- Are you compiling using all your CPU threads? If so, your PC may freeze briefly depends on the hardware.
- Sandbox folder is no longer used, if you look into top level `Makefile`, it compiles Stellar and StellarEditor folder. So please make your changes in StellarEditor/src/ (I should've deleted it or mentioned it in README, my b)
- `Texture2D` class uses a factory pattern, see [here](https://github.com/Gellert5225/StellarEngine/blob/2dc855187b0cbac219ac96d4846abbbdbc27e702/Stellar/src/Stellar/Renderer/Texture.cpp#L19), so instead of casting a raw pointer to smart pointer, try to modify the factory pattern so that it returns a smart pointer directly.

**Comment by Pjsrcool** [comment]
@Gellert5225 
- You're right about the CPU threads. My desktop with 4c/4t completely froze and never resumed. I tried again on my laptop with 6c/12t and it only froze for a few min.
- Alright. I'll move onto StellarEditor and keep design patterns in mind

**Comment by Gellert5225** [comment]
Closed as fixed in #8

**Pull request closed without merging**
